### ISSUE TITLE
Load cell reading issue?

### ISSUE THREAD

**Issue by youngstersp** [olkal/HX711_ADC#10]
When i put the calibration code in for the load cell, I get the output of  zeros over and over again and when I press the load cell it doesn't  read it. Sometimes though when I'm not touching it at all it jumps to high number like 3000. Help

**Comment by olkal** [comment]
Hi! 
Your problem is most likely not related to the library itself.
Please seek advise at https://forum.arduino.cc/ or other similar community.

Olav
