### ISSUE TITLE
Can't get the HX711 to read values from load Cell

### ISSUE THREAD

**Issue by JayShack** [olkal/HX711_ADC#100]
Hi,

I'm using a MEGA 2560 board and set everything up exactly like Indrek did in his youtube tutorial about using a 4 wire load cell and the HX711 board.  Whenever I run the calibration program, the calibration factor always returns as 0.0 and the measurements print as nan after calibration which I assume is because the value it's calculating is 0/0. 

"
Starting...
Startup is complete
***
Start calibration:
Place the load cell an a level stable surface.
Remove any load applied to the load cell.
Send 't' from serial monitor to set the tare offset.
Tare complete
Now, place your known mass on the loadcell.
Then send the weight of this mass (i.e. 100.0) from serial monitor.
Known mass is: 20.00
New calibration value has been set to: 0.00, use this as calibration value (calFactor) in your project sketch.
Save this value to EEPROM adress 0? y/n
Value 0.00 saved to EEPROM address: 0
End calibration
***
To re-calibrate, send 'r' from serial monitor.
For manual edit of the calibration value, send 'c' from serial monitor.
***
Load_cell output val: nan
Load_cell output val: nan
Load_cell output val: nan
Load_cell output val: nan
Load_cell output val: nan
Load_cell output val: nan
Load_cell output val: nan
Load_cell output val: nan
"

 I'm confident in all of my soldered connections and have gotten the load cell to read using the SparkFun OpenScale board which is simpler and has all of the programs loaded onto the board already. I believe my issue is with the code or the way I have it hooked up to the Arduino, which is exactly how it's shown in the Youtube tutorial.

Any ideas or help would be much appreciated.

Thanks,
JayShack

**Comment by olkal** [comment]
Hi!
I have had similar reported issues before that have turned out to be incorrect wiring from the HX711 module to the mcu IO pins, or blown or incompatible IO pins. Please double check that the `clk` and `dout` pin/wiring is correct and that the mcu IO pins that you are using are working, and that you have 5V power to the HX711. 
If you don't find anything wrong, could you try the `Read_1x_load_cell.ino ` example sketch and see what kind of output you get with that?

**Comment by JayShack** [comment]
Hi,

I just checked the pins using this code while nothing was connected to the board

"
int analog0;
int analog1;
int analog2;
int analog3;
int analog4;
int analog5;
int analog6;
int analog7;
int analog8;
int analog9;
int analog10;
int analog11;
int analog12;
int analog13;
int analog14;
int analog15;

int digi1;
int digi2;
int digi3;
int digi4;
int digi5;
int digi6;
int digi7;
int digi8;
int digi9;
int digi10;
int digi11;
int digi12;
int digi13;
int digi14;
int digi15;
int digi16;
int digi17;
int digi18;
int digi19;
int digi20;
int digi21;
int digi22;
int digi23;
int digi24;
int digi25;
int digi26;
int digi27;
int digi28;
int digi29;
int digi30;
int digi31;
int digi32;
int digi33;
int digi34;
int digi35;
int digi36;
int digi37;
int digi38;
int digi39;
int digi40;
int digi41;
int digi42;
int digi43;
int digi44;
int digi45;
int digi46;
int digi47;
int digi48;
int digi49;
int digi50;
int digi51;
int digi52;
int digi53;

void setup() {
  Serial.begin(9600);
}

void loop() {
  analog0 = analogRead(A0);
  analog1 = analogRead(A1);
  analog2 = analogRead(A2);
  analog3 = analogRead(A3);
  analog4 = analogRead(A4);
  analog5 = analogRead(A5);
  analog6 = analogRead(A6);
  analog7 = analogRead(A7);
  analog8 = analogRead(A8);
  analog9 = analogRead(A9);
  analog10 = analogRead(A10);
  analog11 = analogRead(A11);
  analog12 = analogRead(A12);
  analog13 = analogRead(A13);
  analog14 = analogRead(A14);
  analog15 = analogRead(A15);

  digi1 = digitalRead(1);
  digi2 = digitalRead(2);
  digi3 = digitalRead(3);
  digi4 = digitalRead(4);
  digi5 = digitalRead(5);
  digi6 = digitalRead(6);
  digi7 = digitalRead(7);
  digi8 = digitalRead(8);
  digi9 = digitalRead(9);
  digi10 = digitalRead(10);
  digi11 = digitalRead(11);
  digi12 = digitalRead(12);
  digi13 = digitalRead(13);
  digi14 = digitalRead(14);
  digi15 = digitalRead(15);
  digi16 = digitalRead(16);
  digi17 = digitalRead(17);
  digi18 = digitalRead(18);
  digi19 = digitalRead(19);
  digi20 = digitalRead(20);
  digi21 = digitalRead(21);
  digi22 = digitalRead(22);
  digi23 = digitalRead(23);
  digi24 = digitalRead(24);
  digi25 = digitalRead(25);
  digi26 = digitalRead(26);
  digi27 = digitalRead(27);
  digi28 = digitalRead(28);
  digi29 = digitalRead(29);
  digi30 = digitalRead(30);
  digi31 = digitalRead(31);
  digi32 = digitalRead(32);
  digi33 = digitalRead(33);
  digi34 = digitalRead(34);
  digi35 = digitalRead(35);
  digi36 = digitalRead(36);
  digi37 = digitalRead(37);
  digi38 = digitalRead(38);
  digi39 = digitalRead(39);
  digi40 = digitalRead(40);
  digi41 = digitalRead(41);
  digi42 = digitalRead(42);
  digi43 = digitalRead(43);
  digi44 = digitalRead(44);
  digi45 = digitalRead(45);
  digi46 = digitalRead(46);
  digi47 = digitalRead(47);
  digi48 = digitalRead(48);
  digi49 = digitalRead(49);
  digi50 = digitalRead(50);
  digi51 = digitalRead(51);
  digi52 = digitalRead(52);
  digi53 = digitalRead(53);

  Serial.println(analog0);
  Serial.println(analog1);
  Serial.println(analog2);
  Serial.println(analog3);
  Serial.println(analog4);
  Serial.println(analog5);
  Serial.println(analog6);
  Serial.println(analog7);
  Serial.println(analog8);
  Serial.println(analog9);
  Serial.println(analog10);
  Serial.println(analog11);
  Serial.println(analog12);
  Serial.println(analog13);
  Serial.println(analog14);
  Serial.println(analog15);

  Serial.println(digi1);
  Serial.println(digi2);
  Serial.println(digi3);
  Serial.println(digi4);
  Serial.println(digi5);
  Serial.println(digi6);
  Serial.println(digi7);
  Serial.println(digi8);
  Serial.println(digi9);
  Serial.println(digi10);
  Serial.println(digi11);
  Serial.println(digi12);
  Serial.println(digi13);
  Serial.println(digi14);
  Serial.println(digi15);
  Serial.println(digi16);
  Serial.println(digi17);
  Serial.println(digi18);
  Serial.println(digi19);
  Serial.println(digi20);
  Serial.println(digi21);
  Serial.println(digi22);
  Serial.println(digi23);
  Serial.println(digi24);
  Serial.println(digi25);
  Serial.println(digi26);
  Serial.println(digi27);
  Serial.println(digi28);
  Serial.println(digi29);
  Serial.println(digi30);
  Serial.println(digi31);
  Serial.println(digi32);
  Serial.println(digi33);
  Serial.println(digi34);
  Serial.println(digi35);
  Serial.println(digi36);
  Serial.println(digi37);
  Serial.println(digi38);
  Serial.println(digi39);
  Serial.println(digi40);
  Serial.println(digi41);
  Serial.println(digi42);
  Serial.println(digi43);
  Serial.println(digi44);
  Serial.println(digi45);
  Serial.println(digi46);
  Serial.println(digi47);
  Serial.println(digi48);
  Serial.println(digi49);
  Serial.println(digi50);
  Serial.println(digi51);
  Serial.println(digi52);
  Serial.println(digi53);

  delay(100000);
}
"

and the result was 

"
435
408
409
380
375
367
337
351
365
339
380
405
377
352
354
348
1
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
"

I don't know if that's actually telling me anything, but the youtube video I watched seemed to say that the ones that didn't read zero were messed up.

Pins 4 and 5 seem ok and thats what I've been using. I verified the wiring, testing it multiple times with multiple pins ensuring I had the DT and SCK wired correctly and  that the code matched.

Then I ran Read_1x_load_cell.ino and this was the result.

"Starting...
Startup is complete
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
"

Thanks,
JayShack

**Comment by JayShack** [comment]
I couldn't find another way to test the pins, and I'm very new to using Arduino's so I couldn't come up with any ways on my own.

**Comment by olkal** [comment]
That's a funny way of testing the IO pins, I'm not sure what the author is trying to achieve but it doesn't tell you anything useful :) Just moving the `dout` and `sck` to some other pins on a different IO port should be sufficient, for example if you use D4 and D5 now, try to move to D6 and D7. Anyway, there doesn't seem to be any communication between your mcu and the HX711. Is the HX711 module you are using from Sparkfun as well, or is it some chinese make? You don't have a spare HX711 module available to check if there is something wrong with the module itself?

**Comment by JayShack** [comment]
I've ordered an Arduino Uno and a fresh HX711 module to try again with.  So hopefully I'll have some better luck starting over with fresh components.  I used about half of the pins on the MEGA trying to get everything to work so either they were all bad or I had some other issue.  Thanks for all the help, I'll try again in a few days when the new parts get in.

Thanks

**Comment by olkal** [comment]
Okay, good!

**Comment by JayShack** [comment]
It worked first time with the new Arduino Uno and fresh HX711 chip, so it must've been some issue between those two.  Thanks for the speedy replies and help!
