### ISSUE TITLE
Problems with the EEPROM

### ISSUE THREAD

**Issue by burkhardtnb5** [olkal/HX711_ADC#101]
When  I try to run the calibration sketch, it wouldn't compile because "eeprom was not declared in this scope". Also, there isn't any calibration sketch, that doesn't use the eeprom.

**Comment by olkal** [comment]
Hi! The calibration example is intended for mcu's that support internal eeprom, but you should be able to compile and use it if you comment out all lines that call eeprom functions, specifically line 148, 152, 204, 208.

**Comment by burkhardtnb5** [comment]
Thank you, it worked! I really think you should integrate a calibration sketch without the eeprom by default for dumbasses like me

**Comment by burkhardtnb5** [comment]
Nevermind, did it myself and created a pull request
