### ISSUE TITLE
Problem with LoadCell.tareNoDelay();

### ISSUE THREAD

**Issue by prashantlsharma** [olkal/HX711_ADC#104]
Hello,
I have trouble modifying this:
if (Serial.available() > 0) {
if (Serial.available() > 0) {
char inByte = Serial.read();
if (inByte == 't') LoadCell.tareNoDelay();
}
}

I don't want to enter 't' to serial, since i want to process tareNoDelay() function directly even without giving any command since the whole process will be like when we will begin calibrate function there will be no wait placed on the tray and we want tareNoDelay() perform without even in getting any serial command. I have tried using flag or already pre defined char to perform the function but it never worked.
Please help me with thisHello,
I have trouble modifying this:
if (Serial.available() > 0) {
if (Serial.available() > 0) {
char inByte = Serial.read();
if (inByte == 't') LoadCell.tareNoDelay();
}
}

I don't want to enter 't' to serial, since i want to process tareNoDelay() function directly even without giving any command since the whole process will be like when we will begin calibrate function there will be no wait placed on the tray and we want tareNoDelay() perform without even in getting any serial command. I have tried using flag or already pre defined char to perform the function but it never worked.
Please help me with this

**Comment by olkal** [comment]
Hi!
I'm not sure that I understand what you want, but you can call the function `tareNoDelay()` from where ever you want in your code.
