### ISSUE TITLE
tare function does not tare

### ISSUE THREAD

**Issue by strud** [olkal/HX711_ADC#106]
Hi there

I am calling  the tare() function but getting a large residual reading afterwards of about 9000 to 10000 (cal = 1)

What would be the cause of this?

Do you have a limit on how much offset the tare can cope with?

**Comment by olkal** [comment]
Hi, sorry for the delayed response.
There is no limit to the amount of tare offset. I don't know the reason for the issue you have, but perhaps the functions `getTareOffset();` and `setTareOffset();` could be useful to find out what is happening.

**Comment by dennyakbar** [comment]
Hi Olkal, 
For the weighing process, can these two functions be used or what? (setTareOffset and setCalFactor), or just one ?

**Comment by dennyakbar** [comment]
Hi Olkal, 

function setTareOffset(); and setCalFactor(); can be used both or just one is enough ?

**Comment by olkal** [comment]
Hi!
They are totaly different functions and can both be used.
The output is calculated like this (simplified): `outputdata = (data - tareoffset) / calfactor`

**Comment by dennyakbar** [comment]
Olkal, thank you.
