### ISSUE TITLE
Prevent Resetting of Null Weight when using HX711 with a load cell

### ISSUE THREAD

**Issue by atharvaaalok** [olkal/HX711_ADC#107]
Hello,
First of all, thank you for creating this library for the HX711!
I am currently stuck with making changes so that if a weight is already put on the load cell on startup it doesn't get treated as the 0 value.
If possible, please have a look at my question in detail [here](https://arduino.stackexchange.com/questions/90184/prevent-resetting-of-null-weight-when-using-hx711-with-a-load-cell).
Thanks!

**Comment by olkal** [comment]
Hi
To do what you want you have to first set the tare offset, then store this value in EEPROM and then retreive and set this value as tare offset on the next boot.
See example file `Persistent_zero_offset.ino`.
