### ISSUE TITLE
Read Raw data withouth smoothing.

### ISSUE THREAD

**Issue by joseluislucas** [olkal/HX711_ADC#109]
Hi,
Is there a way to read raw data from the sensor (without smoothing)?

Thanks!

**Comment by olkal** [comment]
Hi!
There is no function for this at the moment, but its on my "todo" list.

**Comment by joseluislucas** [comment]
Great! That would be a great way to know if a load cell has the red cable broken, since values are changing so much you can not really see that with the smoothing.
Thanks!
