### ISSUE TITLE
Is there any way to round the output to the nearest whole number?

### ISSUE THREAD

**Issue by youngstersp** [olkal/HX711_ADC#11]
Sorry to keep bothering you.

**Comment by JasonC0x0D** [comment]
getData() returns a float.

Option 1:  Include the Math.h library and use the Round() function.  See https://forum.arduino.cc/index.php?topic=82462.0

Option 2:   Add 0.5 to your float value then cast that value to an integer.  See the second post in this forum.  http://forum.arduino.cc/index.php?topic=331879.0
