### ISSUE TITLE
Have problem with starting the code.

### ISSUE THREAD

**Issue by nqkoisirobo22** [olkal/HX711_ADC#114]
![error in code](https://user-images.githubusercontent.com/120491931/207381429-736bb481-7e28-44d1-a807-1be3bdc0575e.PNG)
Have you ever met anything like this before ?

**Comment by olkal** [comment]
Hi! You need to set the terminal window baud rate to the same as in your sketch (57600)
![image](https://user-images.githubusercontent.com/2838352/207432634-790d0fd4-7c8c-4614-a95d-f32081a83215.png)

**Comment by nqkoisirobo22** [comment]
Thank you verry much !!! Help a lot
