### ISSUE TITLE
Understanding Multi Point Calibration

### ISSUE THREAD

**Issue by meakashrao** [olkal/HX711_ADC#121]
I just want to understand isn't it better to have a multi point calibration setup, so than an effective measurement range is calibrated. 

There are no examples for this calibration as well.

**Comment by olkal** [comment]
Hi! This library does not have support for multi-point calibration. In my experience the output from most load cells are almost linear, and a single calibration point at at least 25% of the load cell capacity will usually work well for the whole range.

**Comment by meakashrao** [comment]
Thank you
