### ISSUE TITLE
Hi, did the mass value needed for the calibration its unit is gram or something else?

### ISSUE THREAD

**Issue by noobandpro** [olkal/HX711_ADC#130]

**Comment by olkal** [comment]
Hi
The library does not care or expect any particular unit: The unit you choose for calibration known mass input will also be your output unit. 
For example, lets say you use a known mass of 1000 grams when you do the calibration procedure (ref [Calibration.ino](https://github.com/olkal/HX711_ADC/blob/master/examples/Calibration/Calibration.ino) example sketch): If you now give the input 1(kg) when asked for known mass value, your output units will be kg. If you give the input 1000(gram) your output units will be gram. And so on...
