### ISSUE TITLE
How to read the value in setup method 

### ISSUE THREAD

**Issue by Eashubh128** [olkal/HX711_ADC#131]
Hey i have a query , if we can read the value in the setup method or not 
i have used the LoadCell.update() method before using the getData() . But its not working .
Please help , the weight i get in setup method is in negative and wrong , but when i do it in loop method it works . Please help

**Comment by olkal** [comment]
Hi
The library is not really suited for single readings. 
You could try the following: run `LoadCell.update()` inside a `while()` loop until `getDataSetStatus()` returns `true`. Then call `getData()`. If you need it to complete faster, reduce the value of `SAMPLES` in file config.h.

**Comment by Eashubh128** [comment]
Hey , i tried this ,  I have two loadcells connected , out of which  getDataSetStatus returns true for only 1 . 
please help

**Comment by olkal** [comment]
Could you post your code, at least the `setup()` part?
