### ISSUE TITLE
SCK_DELAY also needed for RP2040 / Raspberry Pi Pico

### ISSUE THREAD

**Issue by pkElectronics** [olkal/HX711_ADC#133]
Adding this issue just to raise awareness if someone stumbles across it.

If running on a rp2040 for example on a Raspberry Pi Pico you will also need to change the SCK_DELAY flag to 1 to avoid random sampling glitches.

**Comment by olkal** [comment]
Hi, thanks! I have included this info in the comment. From next release the delay will be enabled as default.
