### ISSUE TITLE
Issue with reading data from load cell

### ISSUE THREAD

**Issue by layaannj** [olkal/HX711_ADC#18]
Hi,

Board  - Arduino uno 
IDE    -     Arduino 1.8.1
Code   -   HX711_ADC/examples/Calibrate/Calibrate.ino
ADC + Amplifier - HX711 Breakout board (Green color)
Sensor  - 1Kg load cell
Vcc - 3.3
Gnd - Gnd pin
data - pin 3
clock -pin 4

I am trying to read data from load cell.I only get the output as 0 sometimes -0.00 even if i put some load on the load cell.

output -
 Wait...
Startup + tare is complete
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00
Load_cell output val: 0.00

some one please help me?

Thank you

**Comment by AJP2511** [comment]
Did you try to use 5vdc? I think load cells don't work with less than 5vdc (HX711 work, but the cell need 5vdc to excitation)

**Comment by layaannj** [comment]
ya i also try with 5v.

**Comment by JM-DfT** [comment]
A load cell is a passive device and also works at 3.3V (but with lower resolution). Did you check if there's clock and data at the HX711 pins? Some HX711 boards have a different order of pins.

**Comment by olkal** [comment]
The tare completes and you seem to get a value from the HX711 (even if it's only 0,00). This should indicate that there is communication between the MCU and the HX711 and that the clock/data wiring is okay. Is it possible that there is someting wrong with the the load cell or the wiring between the load cell and the HX711?

**Comment by layaannj** [comment]
Hai,
Sorry for the late response .The connection are correct i cross checked .Now its giving output like this 
Wait...
Startup + tare is complete
Load_cell output val: 0.00      Load_cell calFactor: 696.00
Load_cell output val: -0.00      Load_cell calFactor: 696.00
Load_cell output val: -0.01      Load_cell calFactor: 696.00
Load_cell output val: -0.05      Load_cell calFactor: 696.00
Load_cell output val: -0.08      Load_cell calFactor: 696.00
Load_cell output val: -0.11      Load_cell calFactor: 696.00
Load_cell output val: -0.13      Load_cell calFactor: 696.00
Load_cell output val: -0.14      Load_cell calFactor: 696.00
Load_cell output val: -0.15      Load_cell calFactor: 696.00
Load_cell output val: -0.17      Load_cell calFactor: 696.00
Load_cell output val: -0.21      Load_cell calFactor: 696.00
Load_cell output val: -0.25      Load_cell calFactor: 696.00
Load_cell output val: -0.31      Load_cell calFactor: 696.00
Load_cell output val: -0.38      Load_cell calFactor: 696.00
 
When i press hard the value will change .when i put 100g it wont show any change.

**Comment by olkal** [comment]
Hi
The library has no units. You set the calFactor so that the output value maches your prefered unit (raw data from HX711 is divided on the calFactor value). 

I don't know how you have cross checked the wiring between the load cell and HX711, but note that the color coding on the load cell wires can be different from batch to batch. Anyway, I don't think this is a library issue, it's most likely hardware related.

**Comment by layaannj** [comment]
Hi,
Thank you for your response.I will check the hardware
