### ISSUE TITLE
Units of measurement

### ISSUE THREAD

**Issue by SloCompTech** [olkal/HX711_ADC#3]
Hi,
I haven't found any units for measurement ? Have I overlooked it or units aren't written anywhere ?

Cheers

**Comment by olkal** [comment]
That's correct, there are no units in the library. The raw data is divided by the scaling/calibration value that you set with the function setCalFactor(float) in setup. So you should be able to adjust this value so that the "readable" output matches your preferred unit. I use gram myself.

**Comment by SloCompTech** [comment]
Thanks, you could put that in readme, because someone may not now this.

Cheers
