### ISSUE TITLE
Function update instead getData?

### ISSUE THREAD

**Issue by MigSanc** [olkal/HX711_ADC#32]
Hi Olav,

Shouldn't the function update() be called, instead of getData()? Otherwise, the stabilization for taring due to initial conversions is not achieved

https://github.com/olkal/HX711_ADC/blob/d8c661a8a54e7f536e7419d362465a52b2e11a4a/src/HX711_ADC.cpp#L50

Best regards,
Miguel

**Comment by olkal** [comment]
You are absolutly right Miguel, thanks! The cpp file has now been updated, release 1.1.6.
