### ISSUE TITLE
sei() and cli() not available on SAMD21 Cortex M0 boards

### ISSUE THREAD

**Issue by HamishB** [olkal/HX711_ADC#4]
Hi,

compiling fails on SAMD21 Cortex M0 boards such as the Adafruit Feather M0 (and Arduino Zero?) as the sei() and cli() functions do not exist there.

Replacing calls to them in smoothedData() with interrupts() and noInterrupts() allows it to build.

see also
  https://github.com/adafruit/Adafruit_TLC59711/issues/7
  https://forum.arduino.cc/index.php?topic=130583.0

thanks,
Hamish

**Comment by olkal** [comment]
Hi
The cli()/sei() are remnants from an older interrupt driven version of the library, they are not needed anymore. Should be okay now, new release 1.0.1.
