### ISSUE TITLE
mutli load cells on single CLK pin

### ISSUE THREAD

**Issue by shmulike** [olkal/HX711_ADC#43]
Hello
Thank you for sharing your code.
One of your examples have 2 load cell, but they use different CLK pin
Any chance there might be possible to hook up multi HX711 boards that share the same CLK pin?

**Comment by olkal** [comment]
In short, no.
Perhaps it could be done, but I think you would have to keep the multiple HX711s in sync and wait for all af them to have completed their conversions, then read the dout pins for every HX711s simultaniously. Such functionality is not included in this library.
