### ISSUE TITLE
Getting Load_cell output val: nan

### ISSUE THREAD

**Issue by jalakamkiran** [olkal/HX711_ADC#44]
![image](https://user-images.githubusercontent.com/39314292/93422879-646e6b00-f8d2-11ea-9ca2-f279d115b8db.png)
 I am using a HX711 amplifier for my load cell..After calibration I am getting value as nan...what does that mean? I am pretty sure that my connections are correct.
Thanks in advance

**Comment by olkal** [comment]
Hi! nan means "not a number". 
Does this happen with one of the example sketches or your own code?
What kind of microcontroller are you using?

**Comment by jalakamkiran** [comment]
Hey @olkal, Thanks for the reply...the problem was not with the code but with the arduino..some how the pins I was using were damaged and didn't give results on those pins..I changed the board and it started working fine..

**Comment by olkal** [comment]
Great!
