### ISSUE TITLE
Inconsistent return types for start() and conversion24bit()

### ISSUE THREAD

**Issue by Srijal97** [olkal/HX711_ADC#48]
The return type for `HX711_ADC::start()` is `int`, though it does not return anything.
The return type for `HX711_ADC::conversion24bit()` is `uint8_t`, though it also returns nothing.

It does compile fins with these errors in Arduino IDE, but I am getting errors in Sloeber. I have fixed them by modifying the source code, I suggest this is done here as well.

**Comment by olkal** [comment]
Thanks, corrected in 1.2.4
