### ISSUE TITLE
Using the library with Arduino MKR 1010 Wifi

### ISSUE THREAD

**Issue by RydellRC** [olkal/HX711_ADC#49]
Hello,

I'm truing to use the library with an Arduino MKR1010 Wifi, however the MKR boards don't have EEPROM. I was wondering if there's any advice on how to get this done.

Thanks!

**Comment by olkal** [comment]
Hi!
Just comment out any code related to EEPROM, i.e. in the example file Read_1x_load_cell.ino it should work if you comment out line 22 `#include <EEPROM.h>` (the reading from EEPROM in line 45 is already commented out). EEPROM is only used in the example files for conveniance, the library itself does not use EEPROM.

**Comment by olkal** [comment]
Closing, as I'm consider this issue solved.
