### ISSUE TITLE
Multiply faster than divide

### ISSUE THREAD

**Issue by MalcolmBoura** [olkal/HX711_ADC#50]
In general multiplication is faster than division. The Atmega 328 (and I assume 168) has hardware multiply but not hardware division so multiply is very much faster. I suggest changing calFactor to a multiplier internally.

calFactorRecip = 1 / calFactor;

and then multiply raw values by calFactorRecip.

I may be able to get a pull request done with proposed changes but I don't know when so I will raise this as an issue.

**Comment by olkal** [comment]
Thanks! Included in 1.2.4
