### ISSUE TITLE
How to switch the AB channel

### ISSUE THREAD

**Issue by dingrenjun** [olkal/HX711_ADC#58]
I need to use a HX711 to connect 2 sensors, how to switch the AB channel, I set 128/32, the channel cannot be switched

**Comment by olkal** [comment]
Hi!
You can select the B-channel like this: `LoadCell.setGain(32);`

However; the library is not really intended for applications where you need to switch back and forth between channel A and B, but it may work if you also set the `calibrationValue` and tare/zero load offset every time you switch. Still, there is only one dataset and until that has been "flushed" with new readings from the selected channel, the average value will be a mix of channel A and B.
A better approach if you need to utilize both channels would probably be to use a seperate instance of the library for each cannel.

Is there a particular reason that you're not using one dedicated HX711 for each loadcell? Thats the best solution.

**Comment by olkal** [comment]
I’m closing this issue because it has been inactive for some time.
Please reopen if you still encounter this issue with the latest version, or if the postings in this thread don't solve your problem .
Thank you!

**Comment by felix-schreib** [comment]
Hi,
i want to use the B channel, for some reason the loadcell only works until half of the specified range in the A channel. Even though I use the correct calibration value. 
Where in `setup()` do i need to call `LoadCell.setGain(32);` ?
Thanks

**Comment by olkal** [comment]
Hi,
you can put `LoadCell.setGain(32);` anywhere after `LoadCell.begin();`. 
Or you can just replace `LoadCell.begin();` with `LoadCell.begin(32);`.

**Comment by felix-schreib** [comment]
Its working great now, thanks you!
