### ISSUE TITLE
no matching function for call to 'HX711_ADC::start(long unsigned int&, boolean&)'

### ISSUE THREAD

**Issue by pchatill** [olkal/HX711_ADC#69]
Hi.
Thanks for your job!
I want to use the calibration.ino file with a CubeCell HTCC-AB02S board with your library HX711_ADC-1.2.7
But I have the issue on Line 44: LoadCell.start(stabilizingtime, _tare);
"no matching function for call to 'HX711_ADC::start(long unsigned int&, boolean&)'"
Any idea?
Thanks a lot!

**Comment by olkal** [comment]
Hi!
Quick answer is that the board is not supported. That said, I'm not sure why it won't compile. 
I tried to install the cubecell package in Arduino board manager to do some testing but I get an error msg: `Error downloading https://resource.heltec.cn/download/package_CubeCell_index.json` ...

**Comment by olkal** [comment]
I’m closing this issue because it has been inactive for some time.
Please reopen if you still encounter this issue with the latest version.
Thank you!
