### ISSUE TITLE
Measurement value decreases.

### ISSUE THREAD

**Issue by viper0078** [olkal/HX711_ADC#76]
I am using a 500g beam type load cell. I used the sample program to calibrate it with 500g weights.
When I measure using Read_1x_Load_cell, the value gradually decreases from 500g. The rate of decrease is slow, and after a few minutes or so, the value decreases by about 1.0g.
Does anyone know the cause of this phenomenon?
Thank you .

**Comment by olkal** [comment]
I’m closing this issue because it has been inactive for some time.
Please reopen if you still encounter this issue with the latest version.
Thank you!
