### ISSUE TITLE
Are the dout and sck pins supposed to be connected to digital pins or analog

### ISSUE THREAD

**Issue by youngstersp** [olkal/HX711_ADC#9]

**Comment by olkal** [comment]
That depends on the microcontroller used, but assuming that you are refering to the Atmega328 you can use any pin exept A6 an A7.

**Comment by youngstersp** [comment]
Also is the library compatible with 4 or more hx711s?

**Comment by olkal** [comment]
Yes, but I have only tested it with 2.
